export const all_colors = [
  { "name": "Acajou", "value": "#4A0100" },
  { "name": "Aigue-marine", "value": "#7FFFD4" },
  { "name": "Aluminium", "value": "#A9A9A9" },
  { "name": "Amarante", "value": "#E52B50" },
  { "name": "Améthyste", "value": "#9966CC" },
  { "name": "Anis", "value": "#B2EC5D" },
  { "name": "Aqua", "value": "#00FFFF" },
  { "name": "Aquamarine", "value": "#7FFFD4" },
  { "name": "Argent", "value": "#C0C0C0" },
  { "name": "Ardoise", "value": "#708090" },
  { "name": "Azalée", "value": "#F7C6C7" },
  { "name": "Aubergine", "value": "#580F41" },
  { "name": "Avocat", "value": "#568203" },
  { "name": "Beige", "value": "#F5F5DC" },
  { "name": "Bisque", "value": "#FFE4C4" },
  { "name": "Blanc", "value": "#FFFFFF" },
  { "name": "Bleu", "value": "#0000FF" },
  { "name": "Bleu acier", "value": "#4682B4" },
  { "name": "Bleu azur", "value": "#007FFF" },
  { "name": "Bleu ciel", "value": "#87CEEB" },
  { "name": "Bleu marine", "value": "#000080" },
  { "name": "Bleu pervenche", "value": "#CCCCFF" },
  { "name": "Bleu roi", "value": "#4169E1" },
  { "name": "Bleu turquoise", "value": "#40E0D0" },
  { "name": "Blé", "value": "#F5DEB3" },
  { "name": "Brique", "value": "#CB4154" },
  { "name": "Bronze", "value": "#CD7F32" },
  { "name": "Bronze foncé", "value": "#8C7853" },
  { "name": "Brou de noix", "value": "#A17A74" },
  { "name": "Buffle", "value": "#DAA520" },
  { "name": "Burgundy", "value": "#800020" },
  { "name": "Béton", "value": "#7D7D7D" },
  { "name": "Canari", "value": "#FFFF99" },
  { "name": "Caramel", "value": "#C68E17" },
  { "name": "Carmine", "value": "#960018" },
  { "name": "Cerise", "value": "#DE3163" },
  { "name": "Chartreuse", "value": "#7FFF00" },
  { "name": "Chocolat", "value": "#7B3F00" },
  { "name": "Ciel", "value": "#87CEEB" },
  { "name": "Citron", "value": "#FFF700" },
  { "name": "Citrouille", "value": "#FF7518" },
  { "name": "Cobalt", "value": "#0047AB" },
  { "name": "Corail", "value": "#FF7F50" },
  { "name": "Corail clair", "value": "#F08080" },
  { "name": "Corail foncé", "value": "#CD5B45" },
  { "name": "Cramoisi", "value": "#DC143C" },
  { "name": "Crème", "value": "#FFFDD0" },
  { "name": "Crimson", "value": "#DC143C" },
  { "name": "Cuivre", "value": "#B87333" },
  { "name": "Cyan", "value": "#00FFFF" },
  { "name": "Dahlia", "value": "#D94F70" },
  { "name": "Daim", "value": "#C49E72" },
  { "name": "Dauphin", "value": "#A9A9A9" },
  { "name": "Ecru", "value": "#C2B280" },
  { "name": "Émeraude", "value": "#50C878" },
  { "name": "Fauve", "value": "#C19A6B" },
  { "name": "Fraise", "value": "#FF2040" },
  { "name": "Framboise", "value": "#E30B5D" },
  { "name": "Fuchsia", "value": "#FF00FF" },
  { "name": "Fumée", "value": "#738276" },
  { "name": "Gazon", "value": "#7CFC00" },
  { "name": "Ginger", "value": "#B06500" },
  { "name": "Grenat", "value": "#733635" },
  { "name": "Grenouille", "value": "#3FFF00" },
  { "name": "Gris", "value": "#808080" },
  { "name": "Gris anthracite", "value": "#2F4F4F" },
  { "name": "Gris clair", "value": "#D3D3D3" },
  { "name": "Gris perle", "value": "#CED2D2" },
  { "name": "Gris souris", "value": "#6D6D6D" },
  { "name": "Iris", "value": "#5A4FCF" },
  { "name": "Indigo", "value": "#4B0082" },
  { "name": "Inox", "value": "#D1D1D1" },
  { "name": "Ivoire", "value": "#FFFFF0" },
  { "name": "Jade", "value": "#00A86B" },
  { "name": "Jaune", "value": "#FFFF00" },
  { "name": "Kaki", "value": "#F0E68C" },
  { "name": "Lagon", "value": "#ACE5EE" },
  { "name": "Lavande", "value": "#E6E6FA" },
  { "name": "Lavandin", "value": "#967BB6" },
  { "name": "Lilas", "value": "#C8A2C8" },
  { "name": "Lime", "value": "#00FF00" },
  { "name": "Lin", "value": "#FAF0E6" },
  { "name": "Litchi", "value": "#D9A6A6" },
  { "name": "Magenta", "value": "#FF00FF" },
  { "name": "Mandarine", "value": "#FF8C00" },
  { "name": "Marron", "value": "#800000" },
  { "name": "Mauve", "value": "#E0B0FF" },
  { "name": "Mauve clair", "value": "#E0B0FF" },
  { "name": "Menthe", "value": "#98FF98" },
  { "name": "Moutarde", "value": "#FFDB58" },
  { "name": "Nacré", "value": "#F0EAD6" },
  { "name": "Navy", "value": "#000080" },
  { "name": "Néon vert", "value": "#39FF14" },
  { "name": "Noir", "value": "#000000" },
  { "name": "Ocre", "value": "#CC7722" },
  { "name": "Olive", "value": "#808000" },
  { "name": "Or", "value": "#FFD700" },
  { "name": "Orchidée", "value": "#DA70D6" },
  { "name": "Orange", "value": "#FFA500" },
  { "name": "Paille", "value": "#FAFAD2" },
  { "name": "Pêche", "value": "#FFE5B4" },
  { "name": "Perle", "value": "#F0EAD6" },
  { "name": "Pervenche", "value": "#CCCCFF" },
  { "name": "Pistache", "value": "#93C572" },
  { "name": "Platine", "value": "#E5E4E2" },
  { "name": "Prune", "value": "#70193D" },
  { "name": "Pumpkin", "value": "#FF7518" },
  { "name": "Quartz", "value": "#51484F" },
  { "name": "Raisin", "value": "#6F2DA8" },
  { "name": "Rouge", "value": "#FF0000" },
  { "name": "Rouge brique", "value": "#CB4154" },
  { "name": "Rouge cerise", "value": "#DE3163" },
  { "name": "Rouge foncé", "value": "#8B0000" },
  { "name": "Rouge vermillon", "value": "#E34234" },
  { "name": "Rouille", "value": "#B7410E" },
  { "name": "Sable", "value": "#F4A460" },
  { "name": "Safran", "value": "#F4C430" },
  { "name": "Safran foncé", "value": "#FF9933" },
  { "name": "Sangria", "value": "#92000A" },
  { "name": "Saumon", "value": "#FA8072" },
  { "name": "Sépia", "value": "#704214" },
  { "name": "Sienne", "value": "#882D17" },
  { "name": "Smaragd", "value": "#50C878" },
  { "name": "Soleil", "value": "#FFD300" },
  { "name": "Soufre", "value": "#FFFF66" },
  { "name": "Taupe", "value": "#483C32" },
  { "name": "Terre de Sienne", "value": "#E97451" },
  { "name": "Terracotta", "value": "#E2725B" },
  { "name": "Topaze", "value": "#FFC87C" },
  { "name": "Turquoise", "value": "#40E0D0" },
  { "name": "Vermillon", "value": "#E34234" },
  { "name": "Vermeil", "value": "#E34234" },
  { "name": "Vert", "value": "#00FF00" },
  { "name": "Vert bouteille", "value": "#006A4E" },
  { "name": "Vert bouteille foncé", "value": "#004225" },
  { "name": "Vert émeraude", "value": "#50C878" },
  { "name": "Vert forêt", "value": "#228B22" },
  { "name": "Vert jade", "value": "#00A86B" },
  { "name": "Vert lime", "value": "#32CD32" },
  { "name": "Vert menthe", "value": "#98FF98" },
  { "name": "Vert olive", "value": "#808000" },
  { "name": "Vert pomme", "value": "#8DB600" },
  { "name": "Vert sapin", "value": "#013220" },
  { "name": "Violet", "value": "#8A2BE2" },
  { "name": "Violet clair", "value": "#D8BFD8" },
  { "name": "Violet foncé", "value": "#9400D3" },
  { "name": "Violine", "value": "#8F00FF" },
  { "name": "Vieux rose", "value": "#C08081" },
  { "name": "Zinzolin", "value": "#70528C" },
  { "name": "Zinc", "value": "#7E7F7E" },
  { "name": "Zéphyr", "value": "#E3F2FD" }
]
